### ISSUE TITLE
Randomly losing connections under emacs-ipython-notebook with version 1.11

### ISSUE THREAD

**Issue by millejoh** [ahyatt/emacs-websocket#58] opened 2019-06-17 16:37 UTC
I have haphazardly documented in millejoh/emacs-ipython-notebook#559. The problems seem to start sometime after commit ahyatt/emacs-websocket@0d96ba2ff5a25c6cd6c66f417cc9b5f38a4308ba.

Unfortunately I have very little information to contribute as all the debug buffer states is `[WS] State change to connection broken by remote peer`. This does appear to be an issue with the current release (1.11) of websocket, though, since if I revert to an earlier version I stop seeing the disconnects.

Let me know if there is anything else I can do to help track down the cause of this.

**Comment by ahyatt** [comment] 2019-06-19 23:50
I'll see if I can reproduce.  None of the commits recently look like they should effect connections at all, although maybe the recent change in error handling behavior caused some hidden problem to surface.  Anyway, if I can reproduce it, I'll fix it.

**Comment by ahyatt** [comment] 2019-06-20 02:22
According to @dickmao, https://github.com/ahyatt/emacs-websocket/pull/59 fixes this issue, which I've merged into head.

Can you confirm this fixes the issue?  If so, I'll rev. the version to =1.11.1=.

**Comment by ahyatt** [comment] 2019-06-20 03:43
I've also made an addition small fix beyond the basic fix @dickmao provided in 37ef222d629a1da06a98530827cf0e9b456cd812.  However, I was never able to reproduce this - any clues how I can try to reproduce this sort of thing in a functional test would help me make sure I don't break you again.

**Comment by dzop** [comment] 2019-06-20 07:45
I ran into this issue as well. The server I was communicating with was closing the websocket connection due to an invalid frame being sent. It looks like `encode-coding-string` causes issues if used in `websocket-mask` that are dependent on the specific byte pattern used for the masking.

Here is a test case that will always fail when `encode-coding-string` is used in `websocket-mask`

```emacs-lisp
(cl-letf ((text "{\"parent_header\":{},\"header\":{\"msg_id\":\"a2940bc8-619e-4872-97bd-4c8d6fb93017\",\"msg_type\":\"history_request\",\"version\":\"5.3\",\"username\":\"n\",\"session\":\"409cf442-74ba-462f-8183-6652503005af\",\"date\":\"2019-06-20T02:17:43.925049-0500\"},\"content\":{\"output\":false,\"raw\":false,\"hist_access_type\":\"tail\",\"n\":100},\"metadata\":{},\"buffers\":[],\"channel\":\"shell\"}")
          ((symbol-function #'websocket-genbytes)
           (lambda (&rest _) "\10\206\356\224")))
  (let ((frame (websocket-read-frame
                (websocket-encode-frame
                 (make-websocket-frame :opcode 'text
                                       :payload (encode-coding-string text 'raw-text)
                                       :completep t)
                 t))))
    (should frame)
    (should (equal (websocket-frame-payload frame) text))))
```

**Comment by millejoh** [comment] 2019-06-20 14:11
@ahyatt - thanks for the quick response. Yes, I can confirm that EIN is working again. I wish I were smart enough to come up with a good test case, but hopefully the one @dzop provided will serve as check against this happening again.

**Closed** 2019-06-20 19:51 UTC
